### ISSUE TITLE
关于YOLOV3+: Assisted Excitation of Activations的一个疑问

### ISSUE THREAD

**Issue by lq0104** [ming71/CV_PaperDaily#1]
> 5. Discussion
>  Excite object regions vs suppress non-object regions?
>  （这一点我的理解不一定对，看原文）作者认为两种机制不同。如果是直接进行不含目标样本的抑制，那么在检测阶段无法获知哪些样本（bbox）是不含样本的，需要进行打分判断（也就是conf置信）；而AE激励响应是直接通过逐步的减少让最终结果只关注到少量的正样本上，这一点学习起来更加容易。

您好，很感谢您的分享，让我也从中了解了这篇文献的思想。有一个问题想跟您讨论下，您在结论时提出：”AE激励响应是直接通过逐步的减少让最终结果只关注到少量的正样本上“，但是我看文中的公式，实际上是一个示性函数乘以1个α因子，而这个因子是逐渐衰减的，训练到最后衰减为0，这时示性函数也就发挥不了作用了，也就是正样本的mask不起作用了，所以到最后不应该是关注所有样本（既有正样本，也包括负样本）才对吗，您能帮忙解释一下吗，或者我的理解有问题？谢谢！

**Comment by ming71** [comment]
“关注少量正样本”的意思是使得模型能够自动聚焦学习到正样本，这是针对检测而言的，不是训练
