### ISSUE TITLE
请问有没有准确率和帧率都比较高的分割算法推荐？

### ISSUE THREAD

**Issue by MaMingyueIT** [ming71/CV_PaperDaily#4]
看了CBNet的论文，感觉帧率有点低了，如果能做到20fps就好了。请问有没有20fps准确率又不错的物体分割算法推荐一下，谢谢！

**Comment by ming71** [comment]
分割关注的相对不多，比较热门的开源的代码如YOLACT和YOLACTv2，SOLO（有复现的），最近刚出的polarmask也可以，这些有的能上30+FPS，性能还不错，不过我没跑过；
没开源的就比较多了论文sota的一大把
